services:
  web:
    build: .
    container_name: bcparks-web
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - WORKERS=${WORKERS}
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

  worker:
    build: .
    container_name: bcparks-worker
    volumes:
      - ./instance:/app/instance
      - ./app:/app/app
      - ./run_worker.py:/app/run_worker.py
    restart: unless-stopped
    command: python run_worker.py
